#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: abc123456
  mvc:
    converters:
      preferred-json-mapper: gson

camunda.bpm.admin-user:
  id: demo
  password: demo


#spring:
#  http:
#    converters:
#      preferred-json-mapper=gson: